version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Paris"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "localrootpwd"
      MYSQL_USER: 'localmachine'
      MYSQL_PASSWORD: 'localpassword'
      MYSQL_DATABASE: 'presta-demo'


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce

  presta-demo:
    image: prestashop/prestashop:1.7
    volumes:
      - ./app/src:/var/www/html
    ports:
      - 8080:80

